using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using WinGuardAgent.Apps;
using WinGuardAgent.Chrome;
using WinGuardAgent.Network;
using WinGuardAgent.Security;
using WinGuardAgent.Storage;
namespace WinGuardAgent.Agent;
public sealed class UpdateManager { public Task CheckAsync(CancellationToken ct=default)=>Task.CompletedTask; }
public sealed class PolicyEngine { private readonly PolicyRepository _policies; public PolicyEngine(PolicyRepository policies)=>_policies=policies; public Task InitializeAsync(CancellationToken ct=default)=>_policies.InitializeAsync(ct); }
public sealed class AgentWorker : BackgroundService { private readonly Database _db; private readonly PolicyEngine _policy; private readonly ProcessBlocker _apps; private readonly InstalledAppDetector _detector; private readonly ChromePolicyManager _chrome; private readonly NetworkProtectionManager _network; private readonly SecurityHardening _security; private readonly TamperProtectionService _tamper; private readonly EventRepository _events; private readonly ILogger<AgentWorker> _log; public AgentWorker(Database db,PolicyEngine policy,ProcessBlocker apps,InstalledAppDetector detector,ChromePolicyManager chrome,NetworkProtectionManager network,SecurityHardening security,TamperProtectionService tamper,EventRepository events,ILogger<AgentWorker> log){_db=db;_policy=policy;_apps=apps;_detector=detector;_chrome=chrome;_network=network;_security=security;_tamper=tamper;_events=events;_log=log;} protected override async Task ExecuteAsync(CancellationToken ct){ await _db.InitializeAsync(ct); await _policy.InitializeAsync(ct); await _security.ApplyAsync(ct); await _chrome.ApplyAsync(ct); await _network.ApplyAsync(ct); await _events.WriteAsync("agent_started",reason:"WinGuard service started",ct:ct); _log.LogInformation("WinGuard Agent started."); while(!ct.IsCancellationRequested){ try { await _apps.EnforceAsync(ct); await _detector.ScanAsync(ct); await _tamper.CheckAsync(ct); await Task.Delay(TimeSpan.FromSeconds(2),ct); } catch(OperationCanceledException) when(ct.IsCancellationRequested){break;} catch(Exception ex){_log.LogError(ex,"WinGuard enforcement cycle failed"); await Task.Delay(TimeSpan.FromSeconds(5),ct);} } } public override async Task StopAsync(CancellationToken ct){ try{await _events.WriteAsync("agent_stopped",reason:"WinGuard service stopped",ct:ct);}catch{} await base.StopAsync(ct); } }
public sealed class RollingFileLoggerProvider : ILoggerProvider { private readonly string _dir; public RollingFileLoggerProvider(string dir)=>_dir=dir; public ILogger CreateLogger(string categoryName)=>new FileLogger(_dir,categoryName); public void Dispose(){} private sealed class FileLogger(string dir,string category):ILogger { public IDisposable? BeginScope<TState>(TState state) where TState:notnull=>null; public bool IsEnabled(LogLevel l)=>l>=LogLevel.Information; public void Log<TState>(LogLevel level,EventId id,TState state,Exception? ex,Func<TState,Exception?,string> formatter){ if(!IsEnabled(level))return; try{Directory.CreateDirectory(dir); File.AppendAllText(Path.Combine(dir,$"winguard-{DateTime.UtcNow:yyyyMMdd}.log"),$"{DateTimeOffset.UtcNow:o} [{level}] {category}: {formatter(state,ex)} {ex}\n");}catch{}} } }